[package]
name = "inference-re"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
ndarray = "0.15"
rusqlite = "0.31"
chrono = { version = "0.4", features = ["serde"] }

[[bin]]
name = "generate"
path = "src/bin/generate.rs"

[[bin]]
name = "chat"
path = "src/bin/chat.rs"
