[package]
name = "inference-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
rust-bert = { version = "0.22", features = ["download-libtorch"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
